In [2]:
# ==============================
# Customer Segmentation Project
# ==============================

# Step 1: Import Libraries
import pandas as pd
from io import StringIO
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import plotly.express as px

# ------------------------------
# Step 2: Load Sample Customer Data
# ------------------------------
csv_data = """CustomerID,Age,Gender,Annual_Income,Spending_Score
1,19,Male,15000,39
2,21,Male,16000,81
3,20,Female,17000,6
4,23,Female,18000,77
5,31,Male,20000,40
6,22,Female,19000,76
7,35,Female,21000,6
8,23,Male,22000,94
9,64,Female,24000,3
10,30,Male,25000,72
"""

# Load data into pandas
data = pd.read_csv(StringIO(csv_data))
print("First 5 rows of data:")
display(data.head())

# ------------------------------
# Step 3: Prepare Data for Clustering
# ------------------------------
features = data[['Age', 'Annual_Income', 'Spending_Score']]

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

# ------------------------------
# Step 4: Apply K-Means Clustering
# ------------------------------
kmeans = KMeans(n_clusters=3, random_state=42)
data['Segment'] = kmeans.fit_predict(X_scaled)

print("Data with Segments:")
display(data)

# ------------------------------
# Step 5: Visualize Segments
# ------------------------------
fig = px.scatter_3d(
    data,
    x='Age',
    y='Annual_Income',
    z='Spending_Score',
    color='Segment',
    hover_data=['CustomerID','Gender'],
    title='Customer Segmentation'
)
fig.show()

# ------------------------------
# Step 6: Analyze Segment Summary (numeric only)
# ------------------------------
numeric_columns = ['Age', 'Annual_Income', 'Spending_Score']  # exclude Gender
segment_summary = data.groupby('Segment')[numeric_columns].mean()
print("Segment Summary (average values per cluster):")
display(segment_summary)

First 5 rows of data:

   CustomerID  Age  Gender  Annual_Income  Spending_Score
0           1   19    Male          15000              39
1           2   21    Male          16000              81
2           3   20  Female          17000               6
3           4   23  Female          18000              77
4           5   31    Male          20000              40

Data with Segments:

   CustomerID  Age  Gender  Annual_Income  Spending_Score  Segment
0           1   19    Male          15000              39        2
1           2   21    Male          16000              81        0
2           3   20  Female          17000               6        2
3           4   23  Female          18000              77        0
4           5   31    Male          20000              40        0
5           6   22  Female          19000              76        0
6           7   35  Female          21000               6        2
7           8   23    Male          22000              94        0
8           9   64  Female          24000               3        1
9          10   30    Male          25000              72        0

Segment Summary (average values per cluster):

               Age  Annual_Income  Spending_Score
Segment
0        25.000000   20000.000000       73.333333
1        64.000000   24000.000000        3.000000
2        24.666667   17666.666667       17.000000